### ISSUE TITLE
Čtení z databáze s inkonzistencemi

### ISSUE THREAD

**Issue by RonikCZ** [Tmthetom/rdb_project#10]
Nejsem si moc jistý, jak ten Dictionary nadatabindovat do toho DataGridView. Možná to nějak jde (přijímám návrhy jak), ale pokud ne, viděl bych dvě řešení:

1) Udělat místo Dictionary obalovací classu, která bude mít dvě properties: laptop a pole inkonzistencí. Případně tři, kde by třetí byla boolean, který by ukazoval, jestli tam nějaká inkonzistence existuje (to by bylo snažší pro ten výpis v tabulce, případně ten sloupec Inconsitency můžeme úplně odstranit). Tuhle classu bychom pak mohli hodit do listu a ten pak předat jako DataSource, pak už by z toho ty properties šlo dostat, akorát by ty zobrazované byly o úroveň hlouběji.

2) Přidat do Laptop classy property pole inkonzistencí, které by bylo implicitně nastavené na samé false (pro parsované laptopy ze souborů). Stejně jako u bodu 1) můžeme přidat boolean ukazující existenci ikonzistence.

**Comment by vaclav-langr** [comment]
Třída Laptop upravena dle bodu 2).
