### ISSUE TITLE
Ukládání vyhledávání do databáze

### ISSUE THREAD

**Issue by RonikCZ** [Tmthetom/rdb_project#11]
Parametry vyhledávání ukládám do třídy DatabaseFilter, připravil jsem k ní override ToString i konstruktor, který ten string naparsuje a vytvoří použitelnou třídu pro vyhledávání. Je potřeba akorát vyřešit ukládání těch vyhledávacích stringů do databáze.

**Comment by vaclav-langr** [comment]
Přidána metoda do konektoru.
