### ISSUE TITLE
Zabarvování podle inkonzistencí

### ISSUE THREAD

**Issue by RonikCZ** [Tmthetom/rdb_project#12]
Bude to fungovat (viz funkce dataGridView_Search_DataBindingComplete, otestoval jsem to na jiném parametru), ale jelikož tam zatím nenačítáme inkonzistence, tak podle nich nemůžeme barvit.

**Comment by Tmthetom** [comment]
Funkce byla přesunuta pomocí #regions pod "**User Interface (Animations, transitions, effects, formating, ...)**" -> "**Search tab (Coloring, Formating)**" -> "**Inconsistency (Coloring)**"

**Comment by RonikCZ** [comment]
Přidáno v posledním mergi.
