### ISSUE TITLE
File Import -> BackgroundWorker

### ISSUE THREAD

**Issue by Tmthetom** [Tmthetom/rdb_project#13]
Je nutné předělat importování nových dat do samostatného vlákna, pomocí Backgroundworkeru.

V regionu "**Import tab (Drag&Drop, OpenFileDialog)**", je původní metoda "**FileLoaded**", kterou je nutné předělat z provádění kódu, na volání metody "**BackgroundWorker_DoWork**", kterou je samozřejmě nutné nejdříve implementovat. Dále je k dispozici metoda "**BackgroundWorker_RunWorkerCompleted**", která bude provádět akce po nahrávání, zřejmě pouze zobrazení počtu přidaných hodnot a její implementace je zatím nedůležitá.

**Comment by RonikCZ** [comment]
Přidáno v posledním mergi.
