### ISSUE TITLE
Filtr -> Zobrazení pravých hodnot + poslední nastavení filtru

### ISSUE THREAD

**Issue by Tmthetom** [Tmthetom/rdb_project#16]
V třídě "**FormFilter**", přesněji její metodě "**InitializeValues**", je nutné načítat reálná maxima dat, která jsou v databázi. Nově na to slouží funkce v databázovém konektoru, která vrací slovník maximálních hodnot přímo z databáze. Je potřeba si dávat pozor, aby po opětovném otevření "**FormFilter**" nebyly maxima nahrazeny maximálními hodnotami z tabulky a ne z databáze.

Hodnoty které mají být načteny:
![vystrizek](https://cloud.githubusercontent.com/assets/18363912/25809756/52a59bf0-340e-11e7-82dd-35871e97ad9b.PNG)

Dále by bylo dobré, aby si filtr pamatovat své poslední nastavení, tedy když otevřu filtr a posledně jsem si nastavil třeba poloviční RAM, tak aby stejná hodnota byla stále zachována na své pozici u všech hodnot. Tento bod není důležitý a pokud nebude splněn, nic se nestane.

**Comment by RonikCZ** [comment]
Hotovo
