### ISSUE TITLE
Tvorba prezentace

### ISSUE THREAD

**Issue by Tmthetom** [Tmthetom/rdb_project#21]
Je nutné udělat prezentaci, která bude shrnovat výsledky naší práce.

> Prezentace by měly probíhat v především 16. 5. a proto vás prosím o připravení krátké prezentace, jak jste řešili semestrální práci (v rozsahu 3 slidů powerpoint, kde zmíníte schéma databáze a pak způsob, jak jste zadané úkoly vyřešili) 

Tvorbu prezentace má přidělenou **Tomáš Moravec**.

**Comment by Tmthetom** [comment]
Hotovo, nyní je ve stavu korektur a tvorby slovního doprovodu.

**Comment by Tmthetom** [comment]
Slovní doprovod dokončen.

**Comment by RonikCZ** [comment]
Odprezentováno.
