### ISSUE TITLE
Tlačítko Result nic nedělá

### ISSUE THREAD

**Issue by RonikCZ** [Tmthetom/rdb_project#24]
Budťo ho dej pryč nebo si vymysli, co bude dělat.

**Comment by vaclav-langr** [comment]
Na tlačítko dát zobrazení okna, ve kterém se vypíšou konzistence podle sériového čísla.
Insert z konektoru vrací list zpráv. Jejich formát: serial:color_consistency,width_consistency,height_consistency,depth_consistency,weight_consistency,display_diagonal_consistency,display_width_consistency,display_height_consistency,display_label_consistency,cpu_type_consistency,cpu_cores_consistency,ram_type_consistency,ram_frequency_consistency,ram_size_consistency,hdd_type_consistency,hdd_size_consistency,os_label_consistency,gpu_type_consistency
Takže jen rozparsovat a ukázat true nebo false.

**Comment by Tmthetom** [comment]
# Původní záměr
Nejedná se o tlačítko, ale o informativní label.
Vedle je label s názvem "**label_NumberOfAdded**" a ten je napojený na funkci s názvem "**ShowNumberOfAddedRows**", k nalezení je pod "**User Interface (Animations, transitions, effects, formating, ...)**" -> "**Add (Drag&Drop, AddedRows)**". Jako parametr bere počet nově přidaných řádků.
Bylo by možné do volat funkci s počtem nově přidaných řádků? Možná by nebylo od věci, přidat tam počet nekonzistentních přidaných záznamů.

# Záměr Špánka?
Nepamatuji si že by chtěl přímo vidět ty nekonzistentní záznamy ihned po přidání, nebo ano? @vaclav-langr , @RonikCZ . Samozřejmě tabulku vyhodit můžeme, ale udělal bych to až v pátek asi... tu první variantu, aby to vypisovalo pouze čísla kolik bylo přidáno nových a kolik z nich bylo nekomzistentní, to mohu upravit ještě dnes.

**Comment by Tmthetom** [comment]
Možná by nebylo od věci, přidat tam ještě počet nekonzistentních přidaných záznamů. Nepamatuji si že by chtěl přímo vidět ty nekonzistentní záznamy ihned po přidání, nebo ano?

**Comment by Tmthetom** [comment]
Samozřejmě tabulku vyhodit můžeme, ale udělal bych to až v pátek asi... Pokud mám do funkce přidat další parametr a upravit texty aby to vypisovalo slušně pouze čísla kolik přidáno a kolik nekonzistencí, to mohu udělat dnes.

**Comment by RonikCZ** [comment]
Počet přidaných řádků by byl jednoduchý (messages.Count), počet nekonzistentních řádků už bude složitější, na to by se musel udělat parser těch messages.

**Comment by vaclav-langr** [comment]
Bod 3. zadání: Na nekonzistentnost pouze upozorněte při importu (ale data se naimportují).

**Comment by Tmthetom** [comment]
Pokud existuje pouze bod číslo 3, udělal bych první variantu a to že uděláme počet nekonzistentních řádků, nebo pouze řekneme, že tam nějaké jsou :D

**Comment by RonikCZ** [comment]
Tak pokud jen prasácky chceme zjistit, jestli je řádek nekonzistentní a neparsovat ho, stačí v něm najít výskyt stringu ',1' 👍

**Comment by Tmthetom** [comment]
Funkce "**ShowNumberOfAddedRows**" upravena, nyní má dva vstupní parametry.

> /// Show number of added rows and inconsistencies in Add tab, after data insert.
   /// param name="rows": Number of new added rows
   /// param name="inconsistencies": Number of inconsistent in new added rows
  ShowNumberOfAddedRows(int rows, int inconsistencies)

**Comment by RonikCZ** [comment]
Hotovo
